services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: servidor_mensajes
    ports:
      - "5672:5672" # El puerto por donde se comunicará Spring Boot
      - "15672:15672" # El puerto para ver la interfaz gráfica
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
